[package]
name = "rage-plugin-gpg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aes-kw = { version = "0.2.1", features = ["std"] }
age.workspace = true
age-core = { version = "0.11.0", features = ["plugin"] }
age-plugin = "0.6.0"
anyhow.workspace = true
clap.workspace = true
hex = "0.4.3"
nom = "8.0.0"
rand = "=0.8.5"
rsa = "0.9.8"
sha2 = "0.10.9"
x25519-dalek = "2.0.1"
