["com.microsoft.Word"]

"Language" = { command = "osascript -e 'tell application \"Microsoft Word\" to return language id of (character before text object of selection)'", mappings = { "french" = "french" } }
