'$schema' = 'https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json'

[general]
allow_concurrent_presets = false # (default: false)

# Optional TCP control server to listen for remote commands, such as stopping/starting a preset.
# Reference: https://github.com/rszyma/kanata-tray/blob/main/doc/control_server.md
control_server_enable = true # (default: false)

[defaults]
#kanata_executable = '~/bin/kanata' # if empty or omitted, system $PATH will be searched.
kanata_config = '' # if empty or not omitted, kanata default config locations will be used.
tcp_port = 5829 # (default: 5829)
autorestart_on_crash = false # (default: false)

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. starting preset).
# Reference: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
frenchkeys = 'french.ico'
qwerty = 'qwerty.ico'
'*' = 'other_layers.ico'

[presets.'main cfg']
kanata_config = '~/dotfiles/kanata.kbd'
autorun = true
layer_icons = { frenchkeys = 'french.ico'}
# kanata_executable = ''
# layer_icons = {  }
# tcp_port = 1234
# extra_args = ['-n', '-c=~/.config/kanata/another.kbd']


